import { Schema, model, Types } from "mongoose";
const egyptianCities = [
  { id: "cairo", label: "Cairo" },
  { id: "alexandria", label: "Alexandria" },
  { id: "giza", label: "Giza" },
  { id: "shubraElkheima", label: "Shubra El-Kheima" },
  { id: "portSaid", label: "Port Said" },
  { id: "suez", label: "Suez" },
  { id: "luxor", label: "Luxor" },
  { id: "mansoura", label: "Mansoura" },
  { id: "elMahallaElKubra", label: "El-Mahalla El-Kubra" },
  { id: "tanta", label: "Tanta" },
  { id: "asyut", label: "Asyut" },
  { id: "ismailia", label: "Ismailia" },
  { id: "fayyum", label: "Fayyum" },
  { id: "zagazig", label: "Zagazig" },
  { id: "aswan", label: "Aswan" },
  { id: "damietta", label: "Damietta" },
  { id: "beniSuef", label: "Beni Suef" },
  { id: "qena", label: "Qena" },
  { id: "sohag", label: "Sohag" },
  { id: "hurghada", label: "Hurghada" },
  { id: "6thOfOctoberCity", label: "6th of October City" },
  { id: "shibinElKom", label: "Shibin El Kom" },
  { id: "banha", label: "Banha" },
  { id: "10thOfRamadanCity", label: "10th of Ramadan City" },
  { id: "idfu", label: "Idfu" },
  { id: "mitGhamr", label: "Mit Ghamr" },
  { id: "AlHamidiyya", label: "Al-Hamidiyya" },
  { id: "qalyub", label: "Qalyub" },
  { id: "abuKabir", label: "Abu Kabir" },
  { id: "girga", label: "Girga" },
  { id: "baniMazar", label: "Bani Mazar" },
  { id: "newCairo", label: "New Cairo" },
  { id: "siwa", label: "Siwa" },
  { id: "eltor", label: "El Tor" },
  { id: "dahab", label: "Dahab" },
  { id: "rasGharib", label: "Ras Gharib" },
  { id: "qus", label: "Qus" },
  { id: "abnub", label: "Abnub" },
  { id: "badr", label: "Badr" },
  { id: "samalut", label: "Samalut" },
  { id: "ashmun", label: "Ashmun" },
  { id: "aja", label: "Aja" },
  { id: "ibsheway", label: "Ibsheway" },
  { id: "tamiya", label: "Tamiya" },
  { id: "dikirnis", label: "Dikirnis" },
  { id: "manzalah", label: "Manzalah" },
  { id: "alQanatirAlKhayriyyah", label: "Al-Qanatir Al-Khayriyyah" },
  { id: "minuf", label: "Minuf" },
  { id: "kafrAlZayyat", label: "Kafr Al-Zayyat" },
  { id: "dayrut", label: "Dayrut" },
  { id: "kafrAlDawwar", label: "Kafr al-Dawwar" },
  { id: "akhmim", label: "Akhmim" },
  { id: "sidiBarrani", label: "Sidi Barrani" },
  { id: "alQusayr", label: "Al Qusayr" },
  { id: "safaga", label: "Safaga" },
  { id: "marsaAlam", label: "Marsa Alam" },
  { id: "nagHammadi", label: "Nag Hammadi" },
  { id: "alFashn", label: "Al Fashn" },
  { id: "tala", label: "Tala" },
  { id: "matruh", label: "Matruh" },
  { id: "baltim", label: "Baltim" },
  { id: "alManzilah", label: "Al Manzilah" },
  { id: "abuHammad", label: "Abu Hammad" },
  { id: "sidiSalim", label: "Sidi Salim" },
  { id: "alAlamayn", label: "Al Alamayn" },
  { id: "alHawamidiyah", label: "Al Hawamidiyah" },
  { id: "abuTij", label: "Abu Tij" },
  { id: "alayyat", label: "Al Ayyat" },
  { id: "talAlKebir", label: "Tal al Kebir" },
  { id: "ainSukhna", label: "Ain Sukhna" },
  { id: "rafah", label: "Rafah" },
  { id: "desouk", label: "Desouk" },
  { id: "mallawi", label: "Mallawi" },
  { id: "samannud", label: "Samannud" },
  { id: "sharmElSheikh", label: "Sharm El-Sheikh" },
  { id: "arish", label: "Arish" },
  { id: "damanhur", label: "Damanhur" },
  { id: "kafrElSheikh", label: "Kafr el-Sheikh" },
  { id: "faraskur", label: "Faraskur" },
  { id: "minya", label: "Minya" },
  { id: "bilbays", label: "Bilbays" },
  { id: "ashmun", label: "Ashmun" },
  { id: "faiyum", label: "Faiyum" },
  { id: "dairut", label: "Dairut" },
  { id: "edfu", label: "Edfu" },
];

const propertySchema = new Schema(
  {
    name: {
      type: String,
      required: [true, "name is required"],
      min: [3, "min length 3 char"],
      max: [30, "max length 30 char"],
    },
    description: {
      type: String,
      min: [3, "min length 3 char"],
      max: [100, "max length 30 char"],
    },
    mainImage: {
      type: Object,
      required: [true, "mainImage is required"],
    },
    coverImages: [{ type: Object }],
    city: {
      type: String,
      required: [true, "city is required"],
      enum: egyptianCities.map((city) => city.id),
      default: "Cairo",
    },
    area: {
      type: String,
      required: [true, "area is required"],
      enum: [
        "newCapitalCity",
        "mustaqbalCity",
        "ainSokhna",
        "elGouna",
        "newHeliopolis",
      ],
      //   default: "newCapitalCity",
    },
    price: {
      type: Number,
      min: 1,
    },
    purpose: {
      type: String,
      enum: ["buy", "rent"],
      default: "rent",
    },
    use: {
      type: String,
      enum: ["commercial", "residential", "apartment", "duplexes", "villa"],
      default: "commercial",
    },
    bedrooms: {
      type: String,
    },
    bathrooms: {
      type: Number,
    },
    priceRange: {
      min: {
        type: Number,
        min: 1,
      },
      max: {
        type: Number,
        min: 1,
      },
    },
    currency: {
      type: String,
      enum: ["USD", "EGP", "SAR", "EUR", "AED"],
      default: "EGP",
    },
    customId: String,
    addedBy: {
      type: Types.ObjectId,
      required: [true, "userId is required"],
      ref: "User",
    },
    updatedBy: {
      type: Types.ObjectId,
      ref: "User",
    },
    isDeleted: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  }
);
const propertyModel = model("Property", propertySchema);
export default propertyModel;
